[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.55.0",
    "fastapi>=0.115.14",
    "gradio>=5.35.0",
    "openai>=1.93.0",
    "requests>=2.32.4",
    "uvicorn>=0.34.3",
]
